environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: macos-monterey
    QTVER: 6.6
    OS: macOS
    EXT: tar.gz

install:
    - git submodule update --init
    - sh: bash .ci/install.sh

before_build:
    - cmd: set PATH=%QTPATH%\bin;%PATH%
    - cmd: call %VCVARSALLPATH%

build_script:
    - mkdir build
    - cd build
    - cmd: cmake -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DTEST=ON ../
    - sh: bash ../.ci/build.sh
    - cmake --build . -j 4
    - ctest -V

after_build:
    - cd ..
    - sh: bash .ci/after_build.sh

artifacts:
- path: PokeFinder-%OS%.%EXT%
- path: PokeFinder-%OS%.%EXT%.sha256

deploy:
    provider: GitHub
    description: ''
    auth_token:
        secure: SFsouaBlVG46u5QjtuDZMhTxq9FHVPr1BRF6YwNJhOtlj+vk707p3MEzHttr7Vep
    artifact: PokeFinder-%OS%.%EXT%,PokeFinder-%OS%.%EXT%.sha256
    on:
        APPVEYOR_REPO_TAG: true
